---
name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [$default-branch, dev]
  pull_request:
    branches: [$default-branch]

jobs:
  stylelint:
    name: stylelint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install stylelint
        run: |
          npm install stylelint

      - name: Run stylelint
        run: npx stylelint "src/**/*.css"
          --format github
          --output-file stylelint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: stylelint-results.sarif
          wait-for-processing: true
